-- =========================================================
-- TVARIT HEALTHCARE NETWORK: PATIENTS TABLE SCHEMA & POLICIES
-- Execute this SQL query in Supabase Dashboard -> SQL Editor
-- =========================================================

-- 1. Create Patient Table
CREATE TABLE IF NOT EXISTS public.patients (
    id TEXT PRIMARY KEY,                       -- Patient Identifier (e.g. PAT-8492)
    full_name TEXT NOT NULL,                    -- Patient Full Name
    age INTEGER NOT NULL,                       -- Age
    gender TEXT DEFAULT 'Male',                 -- Gender (Male/Female/Other)
    phone TEXT,                                 -- Phone Number
    symptoms TEXT[] DEFAULT '{}',               -- Array of symptoms (e.g. {'Chest Pain', 'Fever'})
    duration_days INTEGER DEFAULT 1,            -- Symptom duration in days
    severity_1to10 INTEGER DEFAULT 5,           -- Pain/Severity rating 1-10
    bp TEXT DEFAULT '120/80',                   -- Blood Pressure (mmHg)
    pulse INTEGER DEFAULT 80,                   -- Pulse Rate (bpm)
    temp_f NUMERIC(4, 1) DEFAULT 98.6,          -- Body Temp in Fahrenheit
    spo2 INTEGER DEFAULT 97,                    -- SpO2 Oxygen percentage
    triage_level TEXT DEFAULT 'GREEN',          -- RED, YELLOW, or GREEN
    triage_reason TEXT,                         -- Clinical explanation generated by Matrix
    referral_pass TEXT,                         -- JSON string representation of referral pass
    created_at TIMESTAMPTZ DEFAULT NOW(),       -- Timestamp of registration
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Index on Phone Number for Fast Patient Search
CREATE INDEX IF NOT EXISTS idx_patients_phone ON public.patients(phone);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;


-- 3. Create RLS Policies for Anonymous & Authenticated Access
DROP POLICY IF EXISTS "Allow public read access to patients" ON public.patients;
CREATE POLICY "Allow public read access to patients"
ON public.patients FOR SELECT
USING (true);

DROP POLICY IF EXISTS "Allow public insert access to patients" ON public.patients;
CREATE POLICY "Allow public insert access to patients"
ON public.patients FOR INSERT
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update access to patients" ON public.patients;
CREATE POLICY "Allow public update access to patients"
ON public.patients FOR UPDATE
USING (true);

-- 4. Insert Seed Patients for Testing
INSERT INTO public.patients (id, full_name, age, gender, phone, symptoms, duration_days, severity_1to10, bp, pulse, temp_f, spo2, triage_level, triage_reason)
VALUES 
  ('PAT-8491', 'Rajesh Kumar', 52, 'Male', '+91 98765 43210', ARRAY['Chest Pain', 'Difficulty Breathing'], 1, 9, '160/100', 118, 98.6, 88, 'RED', 'CRITICAL: SpO2 88% (<90%) & Chest Pain detected. High Risk for Acute Myocardial Infarction.'),
  ('PAT-8492', 'Sunita Devi', 38, 'Female', '+91 98123 55678', ARRAY['Severe Bleeding', 'Compound Fracture'], 1, 8, '90/60', 125, 99.1, 94, 'RED', 'CRITICAL: Massive blood loss & hypotensive BP 90/60.'),
  ('PAT-8493', 'Ramesh Patel', 45, 'Male', '+91 97654 32109', ARRAY['Fever', 'Abdominal Pain'], 4, 6, '120/80', 92, 102.4, 96, 'YELLOW', 'URGENT: High fever >3 days & severe abdominal tenderness.')
ON CONFLICT (id) DO UPDATE 
SET full_name = EXCLUDED.full_name,
    triage_level = EXCLUDED.triage_level;
